[workspace]
resolver = "2"

members = [
    "crates/*"
]

[workspace.dependencies]
uuid = "1.18.1"
indexmap = "2.12.1"
anyhow = "1.0.100"
tokio = "1.48.0"
async-trait = "0.1.89"
serde = "1.0"
chrono = "0.4"
